Description:  Linux Web Server
Parameters:
  LatestAmiId:
    Description: AMI Linux EC2 
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
Resources:
  webserver1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: "t2.micro"
      ImageId: !Ref LatestAmiId
      SecurityGroupIds: 
        - !Ref WebserverSecurityGroup
      Tags:
        - Key: Name
          Value: webserver1
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y
          yum install httpd -y
          service httpd start
          chkconfig httpd on
          cd /var/www/html
          echo "<br>" >> index.html
          echo "<h1><b>Linux Web Server</b></h1>" >>index.html
          echo "<h1>made by: Azizul maqsud</h1>" >>index.html
          echo "<h2>Please DO NOT forget to subscribe!</h2>" >>index.html
          echo "<h3>Learn IT with Azizul</h3>" >>index.html
          echo "<b>Here is the Server info, Hostname is:</b>" >> index.html
          curl http://169.254.169.254/latest/meta-data/public-hostname >> index.html
          echo "<br>" >> index.html
          echo "<b>Instance Type is:</b>" >> index.html
          curl http://169.254.169.254/latest/meta-data/instance-type >> index.html
          echo "<br>" >> index.html
          echo "<b>Internal IP Address is:</b> " >> index.html
          curl http://169.254.169.254/latest/meta-data/local-ipv4 >> index.html
          echo "<br><b>External IP Address is: </b>"$'\r' >> index.html
          curl http://169.254.169.254/latest/meta-data/public-ipv4 >> index.html
          echo "<br><b>DNS Address is: </b>"$'\r' >> index.html
          curl http://169.254.169.254/latest/meta-data/public-hostname >> index.html
  WebserverSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable Port 80
      Tags:
      - Key: Name
        Value: webserver-sg
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
